/**
 * Admin demo data — used when Supabase tables are empty.
 * Populated from the real Aorthar Faculty of Product Development curriculum docs.
 */

// ─── Users ───────────────────────────────────────────────────────────────────

export const DEMO_USERS = [
  { id: 'demo-profile-1', user_id: 'demo-user-1', full_name: 'Chukwuemeka Obi',    email: 'admin@aorthar.com',          role: 'admin',       department: null,                    created_at: '2026-01-10T09:00:00Z', subscriptions: [] },
  { id: 'demo-profile-2', user_id: 'demo-user-2', full_name: 'Ada Nwosu',           email: 'ada@aorthar.com',            role: 'contributor', department: 'Product Design',        created_at: '2026-01-15T10:30:00Z', subscriptions: [{ status: 'active' }] },
  { id: 'demo-profile-3', user_id: 'demo-user-3', full_name: 'Emeka Eze',           email: 'emeka@aorthar.com',          role: 'contributor', department: 'Backend Engineering',   created_at: '2026-01-18T11:00:00Z', subscriptions: [] },
  { id: 'demo-profile-4', user_id: 'demo-user-4', full_name: 'Chioma Adeyemi',      email: 'chioma.a@student.com',       role: 'student',     department: 'UI/UX Design',          created_at: '2026-02-01T08:00:00Z', subscriptions: [{ status: 'active' }] },
  { id: 'demo-profile-5', user_id: 'demo-user-5', full_name: 'Bayo Adeleke',        email: 'bayo.a@student.com',         role: 'student',     department: 'Product Management',    created_at: '2026-02-03T09:15:00Z', subscriptions: [] },
  { id: 'demo-profile-6', user_id: 'demo-user-6', full_name: 'Fatima Ibrahim',      email: 'fatima.i@student.com',       role: 'student',     department: 'Design Engineering (FE)', created_at: '2026-02-05T10:00:00Z', subscriptions: [{ status: 'active' }] },
  { id: 'demo-profile-7', user_id: 'demo-user-7', full_name: 'Oluwaseun Akinola',   email: 'seun.a@student.com',         role: 'student',     department: 'Backend Engineering',   created_at: '2026-02-08T14:20:00Z', subscriptions: [] },
  { id: 'demo-profile-8', user_id: 'demo-user-8', full_name: 'Ngozi Okonkwo',       email: 'ngozi.o@student.com',        role: 'student',     department: 'Quality Assurance (QA)', created_at: '2026-02-10T08:45:00Z', subscriptions: [] },
];

// ─── Courses ──────────────────────────────────────────────────────────────────

export const DEMO_COURSES = [
  // Year 100 Sem 1 — Shared Foundation
  { id: 'demo-pm101',   code: 'PM101',   name: 'Foundations of Product Management',            status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s1', semesters: { id: 'demo-sem-y100s1', number: 1, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-des101',  code: 'DES101',  name: 'Introduction to Visual Design',                 status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s1', semesters: { id: 'demo-sem-y100s1', number: 1, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-pm103',   code: 'PM103',   name: 'Introduction to Agile & Scrum',                 status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s1', semesters: { id: 'demo-sem-y100s1', number: 1, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-cs101',   code: 'CS101',   name: 'Computer Science Fundamentals',                 status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s1', semesters: { id: 'demo-sem-y100s1', number: 1, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-com101',  code: 'COM101',  name: 'Communication & Stakeholder Management',        status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s1', semesters: { id: 'demo-sem-y100s1', number: 1, years: { id: 'demo-year-100', level: 100 } } },
  // Year 100 Sem 2 — Track Introductions
  { id: 'demo-des102',  code: 'DES102',  name: 'UI Design Fundamentals',                        status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s2', semesters: { id: 'demo-sem-y100s2', number: 2, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-dev101',  code: 'DEV101',  name: 'JavaScript Fundamentals & ES6+',                status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s2', semesters: { id: 'demo-sem-y100s2', number: 2, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-dev105',  code: 'DEV105',  name: 'Introduction to Backend Development (Node.js)', status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s2', semesters: { id: 'demo-sem-y100s2', number: 2, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-qa101',   code: 'QA101',   name: 'Introduction to Software Quality Assurance',    status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s2', semesters: { id: 'demo-sem-y100s2', number: 2, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-scr101',  code: 'SCR101',  name: 'Agile Principles & Scrum Mastery',              status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s2', semesters: { id: 'demo-sem-y100s2', number: 2, years: { id: 'demo-year-100', level: 100 } } },
  { id: 'demo-uxr102',  code: 'UXR102',  name: 'Fundamentals of User Research',                 status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y100s2', semesters: { id: 'demo-sem-y100s2', number: 2, years: { id: 'demo-year-100', level: 100 } } },
  // Year 200 Sem 1
  { id: 'demo-pm201',   code: 'PM201',   name: 'Product Roadmapping & Strategy',                status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y200s1', semesters: { id: 'demo-sem-y200s1', number: 1, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-des201',  code: 'DES201',  name: 'Advanced UI & Layout Systems',                  status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y200s1', semesters: { id: 'demo-sem-y200s1', number: 1, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-dev201',  code: 'DEV201',  name: 'Advanced React: Hooks & Context',               status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y200s1', semesters: { id: 'demo-sem-y200s1', number: 1, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-sec201',  code: 'SEC201',  name: 'Authentication & Authorization (JWT, OAuth)',    status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y200s1', semesters: { id: 'demo-sem-y200s1', number: 1, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-scr201',  code: 'SCR201',  name: 'Scaling Agile Frameworks (SAFe, LeSS)',         status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y200s1', semesters: { id: 'demo-sem-y200s1', number: 1, years: { id: 'demo-year-200', level: 200 } } },
  // Year 200 Sem 2
  { id: 'demo-pm204',   code: 'PM204',   name: 'Growth Hacking & Product-Led Growth',           status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y200s2', semesters: { id: 'demo-sem-y200s2', number: 2, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-des202',  code: 'DES202',  name: 'Interaction Design Principles',                 status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y200s2', semesters: { id: 'demo-sem-y200s2', number: 2, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-dev202',  code: 'DEV202',  name: 'TypeScript Fundamentals',                       status: 'draft',     is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y200s2', semesters: { id: 'demo-sem-y200s2', number: 2, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-qa202',   code: 'QA202',   name: 'Backend Testing Strategies',                    status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y200s2', semesters: { id: 'demo-sem-y200s2', number: 2, years: { id: 'demo-year-200', level: 200 } } },
  { id: 'demo-ops202',  code: 'OPS202',  name: 'Introduction to DevOps & CI/CD',                status: 'published', is_premium: false, credit_units: 3, pass_mark: 60, semester_id: 'demo-sem-y200s2', semesters: { id: 'demo-sem-y200s2', number: 2, years: { id: 'demo-year-200', level: 200 } } },
  // Year 300 Sem 1
  { id: 'demo-pm301',   code: 'PM301',   name: 'Advanced Product Strategy & Portfolio Management', status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s1', semesters: { id: 'demo-sem-y300s1', number: 1, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-des301',  code: 'DES301',  name: 'Building & Maintaining Design Systems',          status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s1', semesters: { id: 'demo-sem-y300s1', number: 1, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-dev301',  code: 'DEV301',  name: 'Frontend System Design',                         status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s1', semesters: { id: 'demo-sem-y300s1', number: 1, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-arc301',  code: 'ARC301',  name: 'System Design Fundamentals',                     status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s1', semesters: { id: 'demo-sem-y300s1', number: 1, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-scr301',  code: 'SCR301',  name: 'Agile Coaching & Transformation',                status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s1', semesters: { id: 'demo-sem-y300s1', number: 1, years: { id: 'demo-year-300', level: 300 } } },
  // Year 300 Sem 2
  { id: 'demo-pm302',   code: 'PM302',   name: 'Product Leadership & Team Building',             status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s2', semesters: { id: 'demo-sem-y300s2', number: 2, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-dev302',  code: 'DEV302',  name: 'Server-Side Rendering (Next.js)',                 status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s2', semesters: { id: 'demo-sem-y300s2', number: 2, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-des303',  code: 'DES303',  name: 'Advanced Prototyping & Microinteractions',       status: 'published', is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s2', semesters: { id: 'demo-sem-y300s2', number: 2, years: { id: 'demo-year-300', level: 300 } } },
  { id: 'demo-ops302',  code: 'OPS302',  name: 'DevOps Culture & Practice',                      status: 'draft',     is_premium: false, credit_units: 3, pass_mark: 65, semester_id: 'demo-sem-y300s2', semesters: { id: 'demo-sem-y300s2', number: 2, years: { id: 'demo-year-300', level: 300 } } },
  // Year 400 Sem 1 — Premium
  { id: 'demo-pm401',   code: 'PM401',   name: 'Mastering the PM Interview',                     status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s1', semesters: { id: 'demo-sem-y400s1', number: 1, years: { id: 'demo-year-400', level: 400 } } },
  { id: 'demo-int401',  code: 'INT401',  name: 'Mastering the Design Interview',                  status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s1', semesters: { id: 'demo-sem-y400s1', number: 1, years: { id: 'demo-year-400', level: 400 } } },
  { id: 'demo-int402',  code: 'INT402',  name: 'Mastering the Frontend Interview',                status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s1', semesters: { id: 'demo-sem-y400s1', number: 1, years: { id: 'demo-year-400', level: 400 } } },
  { id: 'demo-int403',  code: 'INT403',  name: 'Mastering the Backend Interview',                 status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s1', semesters: { id: 'demo-sem-y400s1', number: 1, years: { id: 'demo-year-400', level: 400 } } },
  { id: 'demo-int405',  code: 'INT405',  name: 'Mastering the Agile & Ops Interview',             status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s1', semesters: { id: 'demo-sem-y400s1', number: 1, years: { id: 'demo-year-400', level: 400 } } },
  // Year 400 Sem 2 — Capstone (Premium)
  { id: 'demo-cap402',  code: 'CAP402',  name: 'Capstone Project: Build & Launch a Product',     status: 'published', is_premium: true,  credit_units: 6, pass_mark: 70, semester_id: 'demo-sem-y400s2', semesters: { id: 'demo-sem-y400s2', number: 2, years: { id: 'demo-year-400', level: 400 } } },
  { id: 'demo-eth402',  code: 'ETH402',  name: 'Ethics & Responsibility in Technology',           status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s2', semesters: { id: 'demo-sem-y400s2', number: 2, years: { id: 'demo-year-400', level: 400 } } },
  { id: 'demo-team402', code: 'TEAM402', name: 'Mentorship & Public Speaking',                    status: 'published', is_premium: true,  credit_units: 3, pass_mark: 70, semester_id: 'demo-sem-y400s2', semesters: { id: 'demo-sem-y400s2', number: 2, years: { id: 'demo-year-400', level: 400 } } },
];

// ─── Curriculum structure (for /api/admin/curriculum) ────────────────────────

export const DEMO_YEARS = [
  { id: 'demo-year-100', level: 100, name: 'Year 100', semesters: [{ id: 'demo-sem-y100s1', number: 1 }, { id: 'demo-sem-y100s2', number: 2 }] },
  { id: 'demo-year-200', level: 200, name: 'Year 200', semesters: [{ id: 'demo-sem-y200s1', number: 1 }, { id: 'demo-sem-y200s2', number: 2 }] },
  { id: 'demo-year-300', level: 300, name: 'Year 300', semesters: [{ id: 'demo-sem-y300s1', number: 1 }, { id: 'demo-sem-y300s2', number: 2 }] },
  { id: 'demo-year-400', level: 400, name: 'Year 400', semesters: [{ id: 'demo-sem-y400s1', number: 1 }, { id: 'demo-sem-y400s2', number: 2 }] },
];

// ─── Suggestions ──────────────────────────────────────────────────────────────

export const DEMO_SUGGESTIONS = [
  { id: 'demo-sug-1', type: 'video',    status: 'pending',  content: { course_code: 'DEV201', title: 'React Hooks Deep Dive', description: 'Would love a dedicated lesson on useCallback, useMemo and useRef with real-world examples.', suggested_url: 'https://youtube.com/example' }, created_at: '2026-03-01T10:00:00Z', profiles: { full_name: 'Chioma Adeyemi' } },
  { id: 'demo-sug-2', type: 'resource', status: 'pending',  content: { course_code: 'PM201', title: 'Marty Cagan — Inspired', description: '"Inspired: How to Create Tech Products Customers Love" should be required reading for all PM students.', resource_type: 'book' }, created_at: '2026-03-03T14:30:00Z', profiles: { full_name: 'Bayo Adeleke' } },
  { id: 'demo-sug-3', type: 'video',    status: 'approved', content: { course_code: 'DES101', title: 'Nielsen Norman Group — UX Basics Playlist', description: 'The NNG YouTube channel has excellent foundational content that would complement this course.' }, created_at: '2026-02-20T09:00:00Z', profiles: { full_name: 'Fatima Ibrahim' } },
  { id: 'demo-sug-4', type: 'lesson',   status: 'approved', content: { course_code: 'DEV105', title: 'REST API Design Principles', description: 'A dedicated lesson on RESTful API conventions, versioning, and error handling best practices.' }, created_at: '2026-02-25T11:15:00Z', profiles: { full_name: 'Oluwaseun Akinola' } },
  { id: 'demo-sug-5', type: 'resource', status: 'rejected', content: { course_code: 'DES202', title: 'Link to personal blog', description: 'I wrote a blog post about Figma shortcuts.', suggested_url: 'https://personal-blog.example.com' }, created_at: '2026-02-28T16:00:00Z', profiles: { full_name: 'Ngozi Okonkwo' } },
];

// ─── Capstone submissions ─────────────────────────────────────────────────────

export const DEMO_CAPSTONES = [
  { id: 'demo-cap-1', status: 'submitted', description: 'An AI-powered e-commerce recommendation engine built with Next.js, Supabase, and OpenAI. Personalises product suggestions based on browsing history and purchase patterns.', github_url: 'https://github.com/example/ecommerce-ai', live_url: 'https://demo-store.vercel.app', tech_stack: ['Next.js', 'TypeScript', 'Supabase', 'OpenAI API', 'Tailwind CSS'], submitted_at: '2026-03-05T09:30:00Z', created_at: '2026-03-05T09:30:00Z', admin_notes: null, profiles: { full_name: 'Chioma Adeyemi' } },
  { id: 'demo-cap-2', status: 'approved',  description: 'A comprehensive hospital management system handling patient records, appointment scheduling, and billing with role-based access for doctors, nurses, and admin staff.', github_url: 'https://github.com/example/hospital-mgmt', live_url: 'https://hospital-demo.vercel.app', tech_stack: ['React', 'Node.js', 'PostgreSQL', 'Express', 'JWT'], submitted_at: '2026-02-15T14:00:00Z', created_at: '2026-02-15T14:00:00Z', admin_notes: 'Excellent implementation. The RBAC system is well thought out and the code is clean.', profiles: { full_name: 'Fatima Ibrahim' } },
  { id: 'demo-cap-3', status: 'revision',  description: 'A machine learning weather prediction app that forecasts 7-day weather using historical climate data and neural networks.', github_url: 'https://github.com/example/weather-ml', live_url: '', tech_stack: ['Python', 'TensorFlow', 'Flask', 'React', 'Chart.js'], submitted_at: '2026-03-01T10:00:00Z', created_at: '2026-03-01T10:00:00Z', admin_notes: 'Good concept but the live demo link is broken and the README needs more detail on model accuracy metrics. Please resubmit.', profiles: { full_name: 'Oluwaseun Akinola' } },
];

// ─── Transactions ─────────────────────────────────────────────────────────────

export const DEMO_TRANSACTIONS = [
  { id: 'demo-txn-1', status: 'success', amount: 1500000, paystack_reference: 'PAY-20260301-XJKM89', created_at: '2026-03-01T10:15:00Z', profiles: { full_name: 'Chioma Adeyemi',    email: 'chioma.a@student.com' } },
  { id: 'demo-txn-2', status: 'success', amount: 1500000, paystack_reference: 'PAY-20260302-BNPQ14', created_at: '2026-03-02T14:22:00Z', profiles: { full_name: 'Fatima Ibrahim',      email: 'fatima.i@student.com' } },
  { id: 'demo-txn-3', status: 'success', amount: 1500000, paystack_reference: 'PAY-20260303-CVRT77', created_at: '2026-03-03T09:05:00Z', profiles: { full_name: 'Ada Nwosu',           email: 'ada@aorthar.com' } },
  { id: 'demo-txn-4', status: 'success', amount: 1500000, paystack_reference: 'PAY-20260304-HKWZ22', created_at: '2026-03-04T16:40:00Z', profiles: { full_name: 'Bayo Adeleke',        email: 'bayo.a@student.com' } },
  { id: 'demo-txn-5', status: 'success', amount: 1500000, paystack_reference: 'PAY-20260305-MLRS55', created_at: '2026-03-05T11:30:00Z', profiles: { full_name: 'Ngozi Okonkwo',       email: 'ngozi.o@student.com' } },
  { id: 'demo-txn-6', status: 'failed',  amount: 1500000, paystack_reference: 'PAY-20260303-FAIL01', created_at: '2026-03-03T12:00:00Z', profiles: { full_name: 'Oluwaseun Akinola',   email: 'seun.a@student.com' } },
  { id: 'demo-txn-7', status: 'failed',  amount: 1500000, paystack_reference: 'PAY-20260304-FAIL02', created_at: '2026-03-04T08:15:00Z', profiles: { full_name: 'Emeka Eze',           email: 'emeka@aorthar.com' } },
  { id: 'demo-txn-8', status: 'pending', amount: 1500000, paystack_reference: 'PAY-20260307-PEND01', created_at: '2026-03-07T07:50:00Z', profiles: { full_name: 'Bayo Adeleke',        email: 'bayo.a@student.com' } },
];

// ─── Department enrollment counts ────────────────────────────────────────────

export const DEMO_DEPARTMENT_COUNTS: Record<string, number> = {
  'UI/UX Design': 12,
  'Product Management': 9,
  'Product Design': 8,
  'Design Engineering (FE)': 14,
  'Backend Engineering': 11,
  'Scrum & Agile': 5,
  'Operations': 4,
  'Quality Assurance (QA)': 7,
};

// ─── Question counts per course (for questions overview page) ─────────────────

export const DEMO_QUESTION_COUNTS: Record<string, number> = {
  'demo-pm101':  12, 'demo-des101': 10, 'demo-pm103':  0, 'demo-cs101':  0, 'demo-com101': 0,
  'demo-des102':  8, 'demo-dev101': 12, 'demo-dev105': 12, 'demo-qa101': 10, 'demo-scr101': 10, 'demo-uxr102': 0,
  'demo-pm201':   0, 'demo-des201':  0, 'demo-dev201':  0, 'demo-sec201':  0, 'demo-scr201': 0,
  'demo-pm204':   0, 'demo-des202':  0, 'demo-dev202':  0, 'demo-qa202':   0, 'demo-ops202': 0,
  'demo-pm301':   0, 'demo-des301':  0, 'demo-dev301':  0, 'demo-arc301':  0, 'demo-scr301': 0,
  'demo-pm302':   0, 'demo-dev302':  0, 'demo-des303':  0, 'demo-ops302':  0,
  'demo-pm401':   0, 'demo-int401':  0, 'demo-int402':  0, 'demo-int403':  0, 'demo-int405': 0,
  'demo-cap402':  0, 'demo-eth402':  0, 'demo-team402': 0,
};

// ─── Years with nested semesters + courses (for /admin/courses page) ──────────

export const DEMO_YEARS_WITH_COURSES = [
  {
    id: 'demo-year-100', level: 100, name: 'Year 100',
    semesters: [
      { id: 'demo-sem-y100s1', number: 1, courses: [
        { id: 'demo-pm101',  code: 'PM101',  name: 'Foundations of Product Management',            credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 1 },
        { id: 'demo-des101', code: 'DES101', name: 'Introduction to Visual Design',                 credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 2 },
        { id: 'demo-pm103',  code: 'PM103',  name: 'Introduction to Agile & Scrum',                 credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 3 },
        { id: 'demo-cs101',  code: 'CS101',  name: 'Computer Science Fundamentals',                 credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 4 },
        { id: 'demo-com101', code: 'COM101', name: 'Communication & Stakeholder Management',        credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 5 },
      ]},
      { id: 'demo-sem-y100s2', number: 2, courses: [
        { id: 'demo-des102', code: 'DES102', name: 'UI Design Fundamentals',                        credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 1 },
        { id: 'demo-dev101', code: 'DEV101', name: 'JavaScript Fundamentals & ES6+',                credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 2 },
        { id: 'demo-dev105', code: 'DEV105', name: 'Introduction to Backend Development (Node.js)', credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 3 },
        { id: 'demo-qa101',  code: 'QA101',  name: 'Introduction to Software Quality Assurance',    credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 4 },
        { id: 'demo-scr101', code: 'SCR101', name: 'Agile Principles & Scrum Mastery',              credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 5 },
        { id: 'demo-uxr102', code: 'UXR102', name: 'Fundamentals of User Research',                 credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 6 },
      ]},
    ],
  },
  {
    id: 'demo-year-200', level: 200, name: 'Year 200',
    semesters: [
      { id: 'demo-sem-y200s1', number: 1, courses: [
        { id: 'demo-pm201',  code: 'PM201',  name: 'Product Roadmapping & Strategy',               credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 1 },
        { id: 'demo-des201', code: 'DES201', name: 'Advanced UI & Layout Systems',                  credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 2 },
        { id: 'demo-dev201', code: 'DEV201', name: 'Advanced React: Hooks & Context',               credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 3 },
        { id: 'demo-sec201', code: 'SEC201', name: 'Authentication & Authorization (JWT, OAuth)',    credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 4 },
        { id: 'demo-scr201', code: 'SCR201', name: 'Scaling Agile Frameworks (SAFe, LeSS)',         credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 5 },
      ]},
      { id: 'demo-sem-y200s2', number: 2, courses: [
        { id: 'demo-pm204',  code: 'PM204',  name: 'Growth Hacking & Product-Led Growth',          credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 1 },
        { id: 'demo-des202', code: 'DES202', name: 'Interaction Design Principles',                 credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 2 },
        { id: 'demo-dev202', code: 'DEV202', name: 'TypeScript Fundamentals',                       credit_units: 3, status: 'draft',     is_premium: false, pass_mark: 65, sort_order: 3 },
        { id: 'demo-qa202',  code: 'QA202',  name: 'Backend Testing Strategies',                   credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 4 },
        { id: 'demo-ops202', code: 'OPS202', name: 'Introduction to DevOps & CI/CD',               credit_units: 3, status: 'published', is_premium: false, pass_mark: 60, sort_order: 5 },
      ]},
    ],
  },
  {
    id: 'demo-year-300', level: 300, name: 'Year 300',
    semesters: [
      { id: 'demo-sem-y300s1', number: 1, courses: [
        { id: 'demo-pm301',  code: 'PM301',  name: 'Advanced Product Strategy & Portfolio Management', credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 1 },
        { id: 'demo-des301', code: 'DES301', name: 'Building & Maintaining Design Systems',            credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 2 },
        { id: 'demo-dev301', code: 'DEV301', name: 'Frontend System Design',                           credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 3 },
        { id: 'demo-arc301', code: 'ARC301', name: 'System Design Fundamentals',                       credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 4 },
        { id: 'demo-scr301', code: 'SCR301', name: 'Agile Coaching & Transformation',                  credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 5 },
      ]},
      { id: 'demo-sem-y300s2', number: 2, courses: [
        { id: 'demo-pm302',  code: 'PM302',  name: 'Product Leadership & Team Building',          credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 1 },
        { id: 'demo-dev302', code: 'DEV302', name: 'Server-Side Rendering (Next.js)',              credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 2 },
        { id: 'demo-des303', code: 'DES303', name: 'Advanced Prototyping & Microinteractions',    credit_units: 3, status: 'published', is_premium: false, pass_mark: 65, sort_order: 3 },
        { id: 'demo-ops302', code: 'OPS302', name: 'DevOps Culture & Practice',                    credit_units: 3, status: 'draft',     is_premium: false, pass_mark: 65, sort_order: 4 },
      ]},
    ],
  },
  {
    id: 'demo-year-400', level: 400, name: 'Year 400',
    semesters: [
      { id: 'demo-sem-y400s1', number: 1, courses: [
        { id: 'demo-pm401',  code: 'PM401',  name: 'Mastering the PM Interview',           credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 1 },
        { id: 'demo-int401', code: 'INT401', name: 'Mastering the Design Interview',        credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 2 },
        { id: 'demo-int402', code: 'INT402', name: 'Mastering the Frontend Interview',      credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 3 },
        { id: 'demo-int403', code: 'INT403', name: 'Mastering the Backend Interview',       credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 4 },
        { id: 'demo-int405', code: 'INT405', name: 'Mastering the Agile & Ops Interview',   credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 5 },
      ]},
      { id: 'demo-sem-y400s2', number: 2, courses: [
        { id: 'demo-cap402',  code: 'CAP402',  name: 'Capstone Project: Build & Launch a Product', credit_units: 6, status: 'published', is_premium: true, pass_mark: 70, sort_order: 1 },
        { id: 'demo-eth402',  code: 'ETH402',  name: 'Ethics & Responsibility in Technology',      credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 2 },
        { id: 'demo-team402', code: 'TEAM402', name: 'Mentorship & Public Speaking',               credit_units: 3, status: 'published', is_premium: true, pass_mark: 70, sort_order: 3 },
      ]},
    ],
  },
];

// ─── Course detail map (for /api/admin/courses/[courseId] GET) ────────────────

export const DEMO_COURSE_DETAIL: Record<string, object> = {
  'demo-pm101': { id: 'demo-pm101', code: 'PM101', name: 'Foundations of Product Management', description: 'The cornerstone of the PM track. Introduces students to the role of a PM, the product lifecycle, design thinking, and core frameworks including JTBD, AARRR, and prioritisation methods. Uses case studies from Nigerian startups.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 60, sort_order: 1, semester_id: 'demo-sem-y100s1' },
  'demo-des101': { id: 'demo-des101', code: 'DES101', name: 'Introduction to Visual Design', description: 'Establishes the foundational elements and principles of visual design — line, shape, colour theory, typography, grids, and composition. Forms the bedrock for all future UI and graphic design work.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 60, sort_order: 2, semester_id: 'demo-sem-y100s1' },
  'demo-des102': { id: 'demo-des102', code: 'DES102', name: 'UI Design Fundamentals', description: 'Moves from visual design theory to the practical application of UI design. Students design common components (buttons, forms, cards, nav), learn the 8pt grid system, responsive design, and how to prepare designs for developer handoff in Figma.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 60, sort_order: 1, semester_id: 'demo-sem-y100s2' },
  'demo-dev101': { id: 'demo-dev101', code: 'DEV101', name: 'JavaScript Fundamentals & ES6+', description: 'A comprehensive introduction to JavaScript — from core syntax and data types to modern ES6+ features including arrow functions, destructuring, Promises, and async/await. Builds a strong foundation for React development.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 60, sort_order: 2, semester_id: 'demo-sem-y100s2' },
  'demo-dev105': { id: 'demo-dev105', code: 'DEV105', name: 'Introduction to Backend Development (Node.js)', description: 'Introduces server-side programming using Node.js and Express. Students build HTTP servers, REST APIs, handle middleware, work with the file system, and manage environment variables. Final project: a fully functional CRUD API.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 90, sort_order: 3, semester_id: 'demo-sem-y100s2' },
  'demo-qa101': { id: 'demo-qa101', code: 'QA101', name: 'Introduction to Software Quality Assurance', description: 'Covers the fundamentals of software testing — QA vs QC, SDLC/STLC, black-box vs white-box testing, the bug life cycle, writing test cases, and using Jira for bug tracking. Final assessment includes writing a full bug report and designing test cases.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 60, sort_order: 4, semester_id: 'demo-sem-y100s2' },
  'demo-scr101': { id: 'demo-scr101', code: 'SCR101', name: 'Agile Principles & Scrum Mastery', description: 'Entry point for aspiring Scrum Masters. Covers the Agile Manifesto, the Scrum framework (roles, artifacts, events), servant leadership, sprint facilitation, and an introduction to Kanban. Assessment includes a situational judgment exam and facilitation plan.', credit_units: 3, pass_mark: 60, status: 'published', is_premium: false, quiz_weight: 0.4, exam_weight: 0.6, quiz_attempt_limit: 3, exam_attempt_limit: 2, cooldown_hours: 24, exam_duration_minutes: 60, sort_order: 5, semester_id: 'demo-sem-y100s2' },
};

// ─── Lessons by course (for /api/admin/courses/[courseId]/lessons GET) ────────

export const DEMO_LESSONS_BY_COURSE: Record<string, object[]> = {
  'demo-pm101': [
    { id: 'demo-l-pm101-1',  course_id: 'demo-pm101', title: 'What is a Product Manager?',         sort_order: 1,  duration_minutes: 45, is_published: true, content: '## The PM Role\nPMs sit at the intersection of business, technology, and UX. They define **what** to build and **why** — not how.\n\n- Types: B2B, B2C, Growth, Platform, Technical\n- Key skills: communication, prioritisation, empathy', resources: [{ id: 'demo-r-pm101-1a', type: 'link', title: 'What is Product Management? — ProductPlan', url: 'https://www.productplan.com/what-is-product-management/', sort_order: 1 }, { id: 'demo-r-pm101-1b', type: 'youtube', title: 'The Product Manager Role', url: 'https://www.youtube.com/watch?v=502ILHjX9EE', sort_order: 2 }] },
    { id: 'demo-l-pm101-2',  course_id: 'demo-pm101', title: 'The Product Lifecycle',              sort_order: 2,  duration_minutes: 45, is_published: true, content: '## Lifecycle Stages\n**Ideation → Development → Launch → Growth → Maturity → Decline**\n\nThe goal is to extend the growth phase through continuous discovery and iteration.', resources: [{ id: 'demo-r-pm101-2a', type: 'link', title: 'The Product Life Cycle — ProductPlan', url: 'https://www.productplan.com/learn/product-lifecycle/', sort_order: 1 }] },
    { id: 'demo-l-pm101-3',  course_id: 'demo-pm101', title: 'Design Thinking for PMs',           sort_order: 3,  duration_minutes: 50, is_published: true, content: '## 5 Stages\n1. **Empathise** — understand users\n2. **Define** — frame the problem\n3. **Ideate** — generate solutions\n4. **Prototype** — build to learn\n5. **Test** — validate with real users', resources: [{ id: 'demo-r-pm101-3a', type: 'link', title: "IDEO's Design Thinking", url: 'https://designthinking.ideo.com/', sort_order: 1 }] },
    { id: 'demo-l-pm101-4',  course_id: 'demo-pm101', title: 'Identifying User Needs',            sort_order: 4,  duration_minutes: 45, is_published: true, content: "## Jobs to be Done\n\"People don't buy products; they hire them to make progress in their lives.\" — Clayton Christensen\n\n- Focus on the **job**, not the demographic\n- Identify pain points vs. feature requests", resources: [] },
    { id: 'demo-l-pm101-5',  course_id: 'demo-pm101', title: 'Market & Competitive Analysis',     sort_order: 5,  duration_minutes: 50, is_published: true, content: '## Competitive Analysis\n- SWOT: Strengths, Weaknesses, Opportunities, Threats\n- Direct vs. indirect competitors\n- Market sizing: TAM, SAM, SOM', resources: [] },
    { id: 'demo-l-pm101-6',  course_id: 'demo-pm101', title: 'Introduction to Metrics',           sort_order: 6,  duration_minutes: 45, is_published: true, content: '## AARRR (Pirate Metrics)\n- **Acquisition** — how users find you\n- **Activation** — first great experience\n- **Retention** — do they come back?\n- **Referral** — do they tell others?\n- **Revenue** — do you make money?', resources: [] },
    { id: 'demo-l-pm101-7',  course_id: 'demo-pm101', title: 'What is a Product Vision?',         sort_order: 7,  duration_minutes: 40, is_published: true, content: '## Crafting Vision\nA product vision is the **north star** — it defines why the product exists and what future it is trying to create.\n\n> "To give everyone the power to create and share ideas."', resources: [] },
    { id: 'demo-l-pm101-8',  course_id: 'demo-pm101', title: 'What is a Product Strategy?',       sort_order: 8,  duration_minutes: 45, is_published: true, content: '## Vision vs. Strategy\n- **Vision** = the destination\n- **Strategy** = the route\n\nA good strategy defines your moat, target customers, and strategic pillars.', resources: [] },
    { id: 'demo-l-pm101-9',  course_id: 'demo-pm101', title: 'Introduction to Roadmapping',       sort_order: 9,  duration_minutes: 50, is_published: true, content: '## Outcome vs. Output Roadmaps\n- Output roadmap: list of features with dates ❌\n- Outcome roadmap: problems to solve with measurable goals ✅\n\nRoadmaps communicate **intent**, not commitment.', resources: [] },
    { id: 'demo-l-pm101-10', course_id: 'demo-pm101', title: 'Prioritisation Frameworks',         sort_order: 10, duration_minutes: 55, is_published: true, content: '## Key Frameworks\n- **ICE**: Impact × Confidence ÷ Ease\n- **RICE**: Reach × Impact × Confidence ÷ Effort\n- **MoSCoW**: Must / Should / Could / Won\'t\n- **Kano**: Basic, Performance, Delighters', resources: [] },
    { id: 'demo-l-pm101-11', course_id: 'demo-pm101', title: 'Working with Engineers',            sort_order: 11, duration_minutes: 45, is_published: true, content: '## Building Trust with Engineering\n- Understand tech debt and its cost\n- Write clear tickets with context, not just requirements\n- Involve engineers early in discovery — they spot constraints before you do', resources: [] },
    { id: 'demo-l-pm101-12', course_id: 'demo-pm101', title: 'Working with Designers',            sort_order: 12, duration_minutes: 45, is_published: true, content: '## The PM/Designer Relationship\n- Give designers **problems**, not solutions\n- Participate in critiques; give specific feedback\n- Respect the design process — rushing it creates UX debt', resources: [] },
  ],
  'demo-des101': [
    { id: 'demo-l-des101-1',  course_id: 'demo-des101', title: 'The Elements of Design: Line & Shape',           sort_order: 1,  duration_minutes: 45, is_published: true, content: '## Elements of Design\nLines and shapes are the atoms of all visual composition.\n\n- **Line**: direction, weight, texture\n- **Shape**: geometric vs. organic, positive vs. negative space', resources: [{ id: 'demo-r-des101-1', type: 'youtube', title: 'The 7 Elements of Design', url: 'https://www.youtube.com/watch?v=5kvop_A4Q2I', sort_order: 1 }] },
    { id: 'demo-l-des101-2',  course_id: 'demo-des101', title: 'Form, Texture, & Space',                         sort_order: 2,  duration_minutes: 45, is_published: true, content: '## Adding Depth\n- **Form**: 3D perception on a 2D surface\n- **Texture**: visual vs. tactile\n- **Space**: positive (filled) vs. negative (empty) — white space is not wasted space', resources: [{ id: 'demo-r-des101-2', type: 'youtube', title: 'Space in Graphic Design', url: 'https://www.youtube.com/watch?v=hD-4eoxO0Lw', sort_order: 1 }] },
    { id: 'demo-l-des101-3',  course_id: 'demo-des101', title: 'Balance & Proximity',                            sort_order: 3,  duration_minutes: 45, is_published: true, content: '## Principles of Design\n- **Balance**: symmetrical vs. asymmetrical — both can look intentional\n- **Proximity**: group related items together to imply relationship', resources: [] },
    { id: 'demo-l-des101-4',  course_id: 'demo-des101', title: 'Alignment & Repetition',                         sort_order: 4,  duration_minutes: 45, is_published: true, content: '## Creating Order\n- **Alignment**: invisible grid that ties elements together\n- **Repetition**: consistent use of colour, font, shape — creates brand recognition', resources: [] },
    { id: 'demo-l-des101-5',  course_id: 'demo-des101', title: 'Contrast & White Space',                         sort_order: 5,  duration_minutes: 45, is_published: true, content: '## Making Things Pop\n- **Contrast**: the difference between elements — drives hierarchy\n- **White space**: breathing room that improves readability and perceived quality', resources: [] },
    { id: 'demo-l-des101-6',  course_id: 'demo-des101', title: 'Introduction to Color Theory',                   sort_order: 6,  duration_minutes: 50, is_published: true, content: '## The Colour Wheel\n- Primary → Secondary → Tertiary colours\n- Harmonies: **Complementary**, **Analogous**, **Triadic**, **Split-complementary**', resources: [{ id: 'demo-r-des101-6', type: 'youtube', title: 'Color Theory In Brief', url: 'https://www.youtube.com/watch?v=AvgCkHrcj90', sort_order: 1 }] },
    { id: 'demo-l-des101-7',  course_id: 'demo-des101', title: 'Color Psychology & Application',                 sort_order: 7,  duration_minutes: 50, is_published: true, content: '## Colour & Emotion\n- Red: urgency, energy\n- Blue: trust, calm\n- Yellow: optimism\n- Green: growth, health\n\nBuild palettes from a primary, secondary, and neutral.', resources: [] },
    { id: 'demo-l-des101-8',  course_id: 'demo-des101', title: 'Introduction to Typography',                     sort_order: 8,  duration_minutes: 50, is_published: true, content: '## Anatomy of Type\n- Serif (traditional, trust) vs. Sans-serif (clean, modern)\n- Key terms: baseline, x-height, ascender, descender, kerning, leading', resources: [{ id: 'demo-r-des101-8', type: 'youtube', title: 'A Crash Course in Typography', url: 'https://www.youtube.com/watch?v=gDbKxTCaJpE', sort_order: 1 }] },
    { id: 'demo-l-des101-9',  course_id: 'demo-des101', title: 'Typographic Hierarchy & Pairing',                sort_order: 9,  duration_minutes: 50, is_published: true, content: '## Hierarchy Through Type\n- Use size, weight, and colour to guide the eye\n- Pair fonts with contrast: one display + one body\n- Limit to 2 typefaces per design', resources: [] },
    { id: 'demo-l-des101-10', course_id: 'demo-des101', title: 'Introduction to Grids & Layout',                 sort_order: 10, duration_minutes: 45, is_published: true, content: '## Grid Systems\n- Columns, gutters, and margins\n- 12-column grid for flexibility\n- Grids create rhythm and consistency across screens', resources: [] },
    { id: 'demo-l-des101-11', course_id: 'demo-des101', title: 'Composition & Visual Hierarchy',                 sort_order: 11, duration_minutes: 50, is_published: true, content: '## Directing Attention\nVisual hierarchy tells the eye what to look at first, second, and third.\n\n- Size > Weight > Colour > Position\n- Z-pattern and F-pattern reading flows', resources: [] },
    { id: 'demo-l-des101-12', course_id: 'demo-des101', title: 'Applying Principles to a Simple UI',             sort_order: 12, duration_minutes: 55, is_published: true, content: '## Practical Exercise\nApply all 12 weeks of learning to design a single app screen:\n1. Choose a layout grid\n2. Apply a type scale\n3. Build a colour palette\n4. Apply contrast & hierarchy', resources: [] },
  ],
  'demo-dev101': [
    { id: 'demo-l-dev101-1',  course_id: 'demo-dev101', title: 'Intro to JS & Core Concepts',             sort_order: 1,  duration_minutes: 55, is_published: true, content: '## What is JavaScript?\nThe language of the web — runs in browsers and on servers (Node.js).\n\n- `var` (avoid), `let` (reassignable), `const` (preferred)\n- Data types: string, number, boolean, null, undefined, object, symbol', resources: [] },
    { id: 'demo-l-dev101-2',  course_id: 'demo-dev101', title: 'Operators & Type Coercion',               sort_order: 2,  duration_minutes: 50, is_published: true, content: '## Equality Traps\n- `==` performs type coercion: `"5" == 5` → `true`\n- `===` strict equality: `"5" === 5` → `false`\n\n**Always use `===`.**', resources: [] },
    { id: 'demo-l-dev101-3',  course_id: 'demo-dev101', title: 'Control Flow: Conditionals',              sort_order: 3,  duration_minutes: 50, is_published: true, content: '## Branching Logic\n```js\nif (score >= 60) {\n  console.log("Pass");\n} else {\n  console.log("Fail");\n}\n```\nAlso: ternary `condition ? a : b` and `switch` statements.', resources: [] },
    { id: 'demo-l-dev101-4',  course_id: 'demo-dev101', title: 'Control Flow: Loops',                     sort_order: 4,  duration_minutes: 50, is_published: true, content: '## Iteration\n- `for`: known iterations\n- `while`: unknown iterations\n- `for...of`: arrays\n- `for...in`: object keys\n\n```js\nfor (const item of items) { ... }\n```', resources: [] },
    { id: 'demo-l-dev101-5',  course_id: 'demo-dev101', title: 'Functions',                               sort_order: 5,  duration_minutes: 55, is_published: true, content: '## Reusable Logic\n```js\nfunction add(a, b) { return a + b; }\nconst multiply = (a, b) => a * b;\n```\n\n- Parameters vs. arguments\n- Default parameters: `function greet(name = "World")`', resources: [] },
    { id: 'demo-l-dev101-6',  course_id: 'demo-dev101', title: 'Scope & Closures',                        sort_order: 6,  duration_minutes: 55, is_published: true, content: '## Scope\n- **Global** → accessible everywhere\n- **Local/Block** → inside `{}` only\n\n## Closure\nA function that remembers its outer scope even after it has finished executing.', resources: [] },
    { id: 'demo-l-dev101-7',  course_id: 'demo-dev101', title: 'Arrays & Array Methods',                  sort_order: 7,  duration_minutes: 55, is_published: true, content: '## Essential Methods\n- `map()` — transform each item → new array\n- `filter()` — keep items that pass a test\n- `reduce()` — fold array into a single value\n- `find()`, `some()`, `every()`', resources: [] },
    { id: 'demo-l-dev101-8',  course_id: 'demo-dev101', title: 'Objects',                                 sort_order: 8,  duration_minutes: 50, is_published: true, content: '## Key-Value Pairs\n```js\nconst user = { name: "Ada", role: "PM" };\nuser.name; // dot notation\nuser["role"]; // bracket notation\n```\n\n- Methods are functions inside objects\n- `this` refers to the object', resources: [] },
    { id: 'demo-l-dev101-9',  course_id: 'demo-dev101', title: 'ES6+: Arrow Functions & Template Literals', sort_order: 9,  duration_minutes: 50, is_published: true, content: '## Modern Syntax\n```js\nconst greet = (name) => `Hello, ${name}!`;\n```\n\n- Arrow functions have no `this` of their own\n- Template literals support multi-line strings and interpolation', resources: [] },
    { id: 'demo-l-dev101-10', course_id: 'demo-dev101', title: 'Destructuring & Spread/Rest',             sort_order: 10, duration_minutes: 50, is_published: true, content: '## Clean Extraction\n```js\nconst { name, role } = user;\nconst [first, ...rest] = items;\nconst merged = { ...defaults, ...overrides };\n```', resources: [] },
    { id: 'demo-l-dev101-11', course_id: 'demo-dev101', title: 'Asynchronous JS: Callbacks & Promises',   sort_order: 11, duration_minutes: 60, is_published: true, content: '## The Event Loop\nJS is single-threaded but non-blocking via callbacks and the event queue.\n\n```js\nfetch("/api/data")\n  .then(res => res.json())\n  .catch(err => console.error(err));\n```', resources: [] },
    { id: 'demo-l-dev101-12', course_id: 'demo-dev101', title: 'Asynchronous JS: Async/Await',            sort_order: 12, duration_minutes: 60, is_published: true, content: '## Cleaner Async\n```js\nasync function getData() {\n  try {\n    const res = await fetch("/api/data");\n    const data = await res.json();\n    return data;\n  } catch (err) {\n    console.error(err);\n  }\n}\n```', resources: [] },
  ],
  'demo-dev105': [
    { id: 'demo-l-dev105-1',  course_id: 'demo-dev105', title: 'What is Backend? Intro to Node.js',       sort_order: 1,  duration_minutes: 50, is_published: true, content: '## Client vs. Server\n- **Client**: browser / mobile app — handles UI\n- **Server**: handles data, business logic, authentication\n\nNode.js runs JavaScript outside the browser using the V8 engine. Non-blocking I/O means it can handle many connections simultaneously.', resources: [] },
    { id: 'demo-l-dev105-2',  course_id: 'demo-dev105', title: 'Node.js Modules & require',               sort_order: 2,  duration_minutes: 45, is_published: true, content: '## CommonJS Modules\n```js\n// math.js\nmodule.exports = { add, subtract };\n\n// app.js\nconst { add } = require("./math");\n```\n\nCore modules: `fs`, `path`, `http`, `os`, `events`', resources: [] },
    { id: 'demo-l-dev105-3',  course_id: 'demo-dev105', title: 'The File System (fs) Module',             sort_order: 3,  duration_minutes: 50, is_published: true, content: '## Reading & Writing Files\n```js\nconst fs = require("fs");\nfs.readFile("data.txt", "utf8", (err, data) => {\n  console.log(data);\n});\n```\nSync vs. async methods — always prefer async in production.', resources: [] },
    { id: 'demo-l-dev105-4',  course_id: 'demo-dev105', title: 'The HTTP Module',                         sort_order: 4,  duration_minutes: 50, is_published: true, content: '## Creating a Server\n```js\nconst http = require("http");\nconst server = http.createServer((req, res) => {\n  res.writeHead(200, { "Content-Type": "text/plain" });\n  res.end("Hello, World!");\n});\nserver.listen(3000);\n```', resources: [] },
    { id: 'demo-l-dev105-5',  course_id: 'demo-dev105', title: 'Introduction to Express.js',              sort_order: 5,  duration_minutes: 55, is_published: true, content: '## Why Express?\nExpress is a minimal web framework on top of Node.js that simplifies routing, middleware, and request handling.\n\n```js\nconst express = require("express");\nconst app = express();\napp.listen(3000);\n```', resources: [] },
    { id: 'demo-l-dev105-6',  course_id: 'demo-dev105', title: 'Express.js: Routing',                     sort_order: 6,  duration_minutes: 55, is_published: true, content: '## Route Handlers\n```js\napp.get("/api/users", (req, res) => { ... });\napp.post("/api/users", (req, res) => { ... });\napp.get("/api/users/:id", (req, res) => {\n  const { id } = req.params;\n});\n```', resources: [] },
    { id: 'demo-l-dev105-7',  course_id: 'demo-dev105', title: 'Express.js: Middleware',                  sort_order: 7,  duration_minutes: 55, is_published: true, content: '## What is Middleware?\nFunctions that run between the request and response.\n\n```js\napp.use((req, res, next) => {\n  console.log(`${req.method} ${req.url}`);\n  next(); // pass to next middleware\n});\n```', resources: [] },
    { id: 'demo-l-dev105-8',  course_id: 'demo-dev105', title: 'Handling Requests & Responses',           sort_order: 8,  duration_minutes: 50, is_published: true, content: '## req & res Objects\n- `req.body` — parsed POST body\n- `req.params` — URL parameters\n- `req.query` — query string\n- `res.json({ data })` — send JSON\n- `res.status(404).json({ error: "Not found" })`', resources: [] },
    { id: 'demo-l-dev105-9',  course_id: 'demo-dev105', title: 'Introduction to REST APIs',               sort_order: 9,  duration_minutes: 50, is_published: true, content: '## REST Principles\n- **Stateless**: each request is self-contained\n- **Resource-based URLs**: `/api/courses`, `/api/courses/:id`\n- Use HTTP verbs: `GET` (read), `POST` (create), `PUT/PATCH` (update), `DELETE`', resources: [] },
    { id: 'demo-l-dev105-10', course_id: 'demo-dev105', title: 'Building a Simple CRUD API',              sort_order: 10, duration_minutes: 65, is_published: true, content: '## In-Memory CRUD\nBuild GET, POST, PUT, DELETE endpoints for a `books` resource.\n\n```js\nlet books = [];\napp.get("/api/books", (req, res) => res.json(books));\napp.post("/api/books", (req, res) => { books.push(req.body); res.status(201).json(req.body); });\n```', resources: [] },
    { id: 'demo-l-dev105-11', course_id: 'demo-dev105', title: 'Asynchronous Patterns in Node.js',        sort_order: 11, duration_minutes: 55, is_published: true, content: '## Async in a Server Context\nCallbacks → Promises → Async/Await\n\n```js\napp.get("/api/data", async (req, res) => {\n  const data = await db.query("SELECT * FROM courses");\n  res.json(data);\n});\n```', resources: [] },
    { id: 'demo-l-dev105-12', course_id: 'demo-dev105', title: 'Environment Variables',                   sort_order: 12, duration_minutes: 40, is_published: true, content: '## Managing Secrets\nNever hardcode credentials. Use `.env` files:\n\n```\nDB_URL=postgres://...\nJWT_SECRET=supersecret\n```\n\n```js\nrequire("dotenv").config();\nconst secret = process.env.JWT_SECRET;\n```', resources: [] },
  ],
  'demo-qa101': [
    { id: 'demo-l-qa101-1',  course_id: 'demo-qa101', title: 'What is Quality Assurance?',              sort_order: 1,  duration_minutes: 45, is_published: true, content: '## QA vs. QC\n- **QA** (Quality Assurance) — process-oriented: prevent defects\n- **QC** (Quality Control) — product-oriented: find defects\n\nThe cost of fixing a bug grows exponentially the later it is found in the development cycle.', resources: [{ id: 'demo-r-qa101-1', type: 'youtube', title: 'What is Software Testing?', url: 'https://www.youtube.com/watch?v=u6QfIXgjwGQ', sort_order: 1 }] },
    { id: 'demo-l-qa101-2',  course_id: 'demo-qa101', title: 'SDLC & STLC',                             sort_order: 2,  duration_minutes: 50, is_published: true, content: '## Two Lifecycles\n- **SDLC**: Requirement → Design → Development → Testing → Deployment → Maintenance\n- **STLC**: Requirement Analysis → Test Planning → Environment Setup → Execution → Closure', resources: [] },
    { id: 'demo-l-qa101-3',  course_id: 'demo-qa101', title: 'Types of Testing',                        sort_order: 3,  duration_minutes: 50, is_published: true, content: '## Classification\n- **Functional**: does it do what it should? (Unit, Integration, E2E)\n- **Non-functional**: how well? (Performance, Security, Usability)\n- **Black Box**: test without code knowledge\n- **White Box**: test with code knowledge', resources: [] },
    { id: 'demo-l-qa101-4',  course_id: 'demo-qa101', title: 'The Bug Life Cycle',                      sort_order: 4,  duration_minutes: 45, is_published: true, content: '## Bug States\nNew → Assigned → Open → Fixed → **Retest** → Verified → Closed\n\nA bug can also be: Deferred, Rejected, or Reopened.\n\nThe tester always owns retest verification.', resources: [] },
    { id: 'demo-l-qa101-5',  course_id: 'demo-qa101', title: 'Test Scenarios vs. Test Cases',           sort_order: 5,  duration_minutes: 50, is_published: true, content: '## Definitions\n- **Test Scenario**: high-level "what to test" — e.g., "Verify login works"\n- **Test Case**: step-by-step "how to test" — preconditions, steps, expected result', resources: [] },
    { id: 'demo-l-qa101-6',  course_id: 'demo-qa101', title: 'Writing Effective Test Cases',            sort_order: 6,  duration_minutes: 55, is_published: true, content: '## Test Case Structure\n1. **ID & Title**\n2. **Preconditions** (e.g., user is logged in)\n3. **Test Data**\n4. **Steps** (numbered)\n5. **Expected Result**\n6. **Actual Result** (filled during execution)', resources: [] },
    { id: 'demo-l-qa101-7',  course_id: 'demo-qa101', title: 'Bug Reporting & Tools (Jira)',            sort_order: 7,  duration_minutes: 50, is_published: true, content: '## A Good Bug Report\n- **Title**: concise, specific\n- **Environment**: OS, browser, device\n- **Steps to Reproduce**: numbered, exact\n- **Expected vs. Actual Result**\n- **Attachments**: screenshot, logs, video', resources: [] },
    { id: 'demo-l-qa101-8',  course_id: 'demo-qa101', title: 'Severity vs. Priority',                   sort_order: 8,  duration_minutes: 45, is_published: true, content: '## Two Different Questions\n- **Severity**: how bad is the technical impact? (Critical → High → Medium → Low)\n- **Priority**: how urgently must it be fixed? (business decision)\n\nA typo on the homepage may have Low severity but High priority.', resources: [] },
    { id: 'demo-l-qa101-9',  course_id: 'demo-qa101', title: 'Functional Testing Techniques',          sort_order: 9,  duration_minutes: 55, is_published: true, content: '## Efficient Test Design\n- **Boundary Value Analysis**: test at the edges (min, max, min-1, max+1)\n- **Equivalence Partitioning**: group valid/invalid inputs, test one from each group', resources: [] },
    { id: 'demo-l-qa101-10', course_id: 'demo-qa101', title: 'User Acceptance Testing (UAT)',           sort_order: 10, duration_minutes: 50, is_published: true, content: '## UAT Purpose\nValidate that the system meets business requirements from the **end-user perspective**.\n\n- **Alpha testing**: internal users, controlled environment\n- **Beta testing**: real users, production-like environment', resources: [] },
    { id: 'demo-l-qa101-11', course_id: 'demo-qa101', title: 'Introduction to API Testing',             sort_order: 11, duration_minutes: 55, is_published: true, content: '## Testing APIs with Postman\nAn API is a contract between a client and server. Test it by:\n1. Sending valid requests → verify status 200 + correct response\n2. Sending invalid data → verify correct error codes (400, 401, 404)', resources: [] },
    { id: 'demo-l-qa101-12', course_id: 'demo-qa101', title: 'QA in Agile Teams',                       sort_order: 12, duration_minutes: 45, is_published: true, content: '## Shift-Left Testing\nIn Agile, QA is involved **from day 1**, not just at the end.\n\n- Review acceptance criteria during sprint planning\n- Write test cases alongside development\n- Participate in retrospectives — QA owns quality culture', resources: [] },
  ],
  'demo-scr101': [
    { id: 'demo-l-scr101-1',  course_id: 'demo-scr101', title: 'Waterfall vs. Agile',                   sort_order: 1,  duration_minutes: 45, is_published: true, content: '## Why Waterfall Failed Software\nWaterfall is sequential — requirements, design, build, test, deploy — no going back.\n\nSoftware changes constantly; requirements are never final. **Agile embraces change.**', resources: [] },
    { id: 'demo-l-scr101-2',  course_id: 'demo-scr101', title: 'The Agile Manifesto',                   sort_order: 2,  duration_minutes: 50, is_published: true, content: '## 4 Values\n1. **Individuals & interactions** over processes & tools\n2. **Working software** over comprehensive documentation\n3. **Customer collaboration** over contract negotiation\n4. **Responding to change** over following a plan\n\nThe right side still matters — just less.', resources: [] },
    { id: 'demo-l-scr101-3',  course_id: 'demo-scr101', title: 'Scrum Framework Overview',              sort_order: 3,  duration_minutes: 50, is_published: true, content: '## Empiricism\nScrum is founded on three pillars:\n- **Transparency**: make work visible\n- **Inspection**: regularly review progress\n- **Adaptation**: adjust when something is off\n\nScrum = **Roles + Events + Artifacts**', resources: [] },
    { id: 'demo-l-scr101-4',  course_id: 'demo-scr101', title: 'Scrum Roles: The Scrum Master',         sort_order: 4,  duration_minutes: 50, is_published: true, content: '## Servant Leadership\nThe Scrum Master is **not** a project manager. They:\n- Remove impediments\n- Coach the team on Scrum\n- Protect the team from interruptions\n- Facilitate events — they do not chair them', resources: [] },
    { id: 'demo-l-scr101-5',  course_id: 'demo-scr101', title: 'Scrum Roles: PO & Developers',          sort_order: 5,  duration_minutes: 50, is_published: true, content: '## Accountabilities\n- **Product Owner**: maximises product value, owns the backlog, prioritises\n- **Developers**: self-organising, accountable for the Sprint and the Definition of Done\n\nNo sub-teams, no hierarchy within the Developer group.', resources: [] },
    { id: 'demo-l-scr101-6',  course_id: 'demo-scr101', title: 'Scrum Artifacts: The Backlog',          sort_order: 6,  duration_minutes: 50, is_published: true, content: '## Two Backlogs\n- **Product Backlog**: ordered list of everything the product needs (PO owns)\n- **Sprint Backlog**: items selected for this sprint + the Sprint Goal (Developers own)\n\n**Definition of Done (DoD)**: shared agreement on what "done" means.', resources: [] },
    { id: 'demo-l-scr101-7',  course_id: 'demo-scr101', title: 'Scrum Artifacts: The Increment',        sort_order: 7,  duration_minutes: 45, is_published: true, content: '## Shippable Every Sprint\nThe Increment is the sum of all completed PBIs that meet the DoD.\n\nIt **must** be usable — even if the PO decides not to release it. Technical debt is the enemy of the Increment.', resources: [] },
    { id: 'demo-l-scr101-8',  course_id: 'demo-scr101', title: 'Scrum Events: Sprint Planning',         sort_order: 8,  duration_minutes: 55, is_published: true, content: '## Planning the Sprint\nTimeboxed to 8 hours for a 1-month sprint.\n\n1. **Why?** — agree the Sprint Goal\n2. **What?** — select PBIs from the backlog\n3. **How?** — Developers decompose items into tasks\n\nEstimation: Story Points using Planning Poker.', resources: [] },
    { id: 'demo-l-scr101-9',  course_id: 'demo-scr101', title: 'Scrum Events: Daily Scrum',             sort_order: 9,  duration_minutes: 40, is_published: true, content: '## 15-Minute Synchronisation\nFor Developers only — the Scrum Master facilitates if needed.\n\n3 questions:\n1. What did I do yesterday?\n2. What will I do today?\n3. Any impediments?\n\n**Avoid status reports** — this is for the team.', resources: [] },
    { id: 'demo-l-scr101-10', course_id: 'demo-scr101', title: 'Scrum Events: Sprint Review',           sort_order: 10, duration_minutes: 45, is_published: true, content: '## Inspect the Increment\nTimeboxed to 4 hours. The team demonstrates working software to stakeholders.\n\n- PO explains what was done and what was not\n- Stakeholders give feedback\n- Product Backlog is adapted', resources: [] },
    { id: 'demo-l-scr101-11', course_id: 'demo-scr101', title: 'Scrum Events: Sprint Retrospective',    sort_order: 11, duration_minutes: 50, is_published: true, content: '## Continuous Improvement\nTimeboxed to 3 hours. The team inspects **itself**.\n\n**Start / Stop / Continue** framework:\n- What should we start doing?\n- What should we stop doing?\n- What should we continue doing?', resources: [] },
    { id: 'demo-l-scr101-12', course_id: 'demo-scr101', title: 'Kanban & Scrumban',                     sort_order: 12, duration_minutes: 50, is_published: true, content: '## When to Use Kanban\n- Visualise work on a board (To Do → In Progress → Done)\n- WIP limits prevent context switching\n- **Scrumban**: hybrid — Kanban board inside a Scrum framework\n\nKanban is better for support/ops work; Scrum for product development.', resources: [] },
  ],
};

// ─── Questions by course (for /api/admin/courses/[courseId]/questions GET) ────

export const DEMO_QUESTIONS_BY_COURSE: Record<string, object[]> = {
  'demo-pm101': [
    { id: 'demo-q-pm101-1', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'Which of the following is NOT a primary responsibility of a Product Manager?', options: [{ id: 'a', text: 'Defining the product vision', is_correct: false }, { id: 'b', text: 'Writing the code for new features', is_correct: true }, { id: 'c', text: 'Prioritising features for development', is_correct: false }, { id: 'd', text: 'Understanding user needs', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-pm101-2', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'In the Product Lifecycle, what stage typically follows "Launch"?', options: [{ id: 'a', text: 'Decline', is_correct: false }, { id: 'b', text: 'Ideation', is_correct: false }, { id: 'c', text: 'Growth', is_correct: true }, { id: 'd', text: 'Maturity', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-pm101-3', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'What is the first step in the Design Thinking process?', options: [{ id: 'a', text: 'Prototype', is_correct: false }, { id: 'b', text: 'Ideate', is_correct: false }, { id: 'c', text: 'Define', is_correct: false }, { id: 'd', text: 'Empathise', is_correct: true }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-pm101-4', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'The "Jobs to be Done" framework focuses on:', options: [{ id: 'a', text: 'The demographic of the user', is_correct: false }, { id: 'b', text: 'The features a product has', is_correct: false }, { id: 'c', text: 'The progress a user is trying to make', is_correct: true }, { id: 'd', text: "The user's past purchase history", is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-pm101-5', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'In the AARRR (Pirate Metrics) framework, what does "Activation" measure?', options: [{ id: 'a', text: 'How users first discover your product', is_correct: false }, { id: 'b', text: "Users' first meaningful experience with the product", is_correct: true }, { id: 'c', text: 'Whether users come back after their first visit', is_correct: false }, { id: 'd', text: 'Revenue generated from users', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-pm101-6', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'Which prioritisation framework ranks features by Reach, Impact, Confidence, and Effort?', options: [{ id: 'a', text: 'MoSCoW', is_correct: false }, { id: 'b', text: 'ICE', is_correct: false }, { id: 'c', text: 'RICE', is_correct: true }, { id: 'd', text: 'Kano', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-pm101-7', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'What is the key difference between a product vision and a product strategy?', options: [{ id: 'a', text: 'Vision is short-term; strategy is long-term', is_correct: false }, { id: 'b', text: 'Vision is the destination; strategy is the route', is_correct: true }, { id: 'c', text: 'Vision is for engineers; strategy is for PMs', is_correct: false }, { id: 'd', text: 'They are the same thing', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-pm101-8', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'An outcome-based roadmap differs from an output-based roadmap in that it:', options: [{ id: 'a', text: 'Lists features with specific delivery dates', is_correct: false }, { id: 'b', text: 'Is only used by engineering teams', is_correct: false }, { id: 'c', text: 'Focuses on problems to solve and measurable goals rather than deliverables', is_correct: true }, { id: 'd', text: 'Cannot be shared with stakeholders', is_correct: false }], is_exam_question: true, difficulty: 3, points: 2 },
    { id: 'demo-q-pm101-9', course_id: 'demo-pm101', type: 'multiple_choice', question_text: 'What is "tech debt" in the context of working with engineers?', options: [{ id: 'a', text: 'The financial cost of building software', is_correct: false }, { id: 'b', text: 'The cost of prioritising speed over code quality, which must be paid back later', is_correct: true }, { id: 'c', text: 'Open-source libraries used in the product', is_correct: false }, { id: 'd', text: 'The number of engineers on the team', is_correct: false }], is_exam_question: true, difficulty: 3, points: 2 },
  ],
  'demo-des101': [
    { id: 'demo-q-des101-1', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'Which of the following is considered an "Element" of design (not a principle)?', options: [{ id: 'a', text: 'Balance', is_correct: false }, { id: 'b', text: 'Contrast', is_correct: false }, { id: 'c', text: 'Shape', is_correct: true }, { id: 'd', text: 'Repetition', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-des101-2', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'The empty area around objects in a design is commonly referred to as:', options: [{ id: 'a', text: 'Positive Space', is_correct: false }, { id: 'b', text: 'Negative Space / White Space', is_correct: true }, { id: 'c', text: 'Texture', is_correct: false }, { id: 'd', text: 'Form', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-des101-3', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'Placing related items close together in a design is an example of which principle?', options: [{ id: 'a', text: 'Proximity', is_correct: true }, { id: 'b', text: 'Alignment', is_correct: false }, { id: 'c', text: 'Contrast', is_correct: false }, { id: 'd', text: 'Balance', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-des101-4', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'Creating a structured and organised look by lining up elements is known as:', options: [{ id: 'a', text: 'Repetition', is_correct: false }, { id: 'b', text: 'Alignment', is_correct: true }, { id: 'c', text: 'Proximity', is_correct: false }, { id: 'd', text: 'Space', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-des101-5', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'Which colour harmony uses colours that are directly opposite each other on the colour wheel?', options: [{ id: 'a', text: 'Analogous', is_correct: false }, { id: 'b', text: 'Triadic', is_correct: false }, { id: 'c', text: 'Complementary', is_correct: true }, { id: 'd', text: 'Split-complementary', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-des101-6', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'In typography, what is the key visual difference between a serif and a sans-serif typeface?', options: [{ id: 'a', text: 'Serifs are always bold; sans-serifs are always light', is_correct: false }, { id: 'b', text: 'Serifs have small decorative strokes at the end of letterforms; sans-serifs do not', is_correct: true }, { id: 'c', text: 'Serifs are used for headings only; sans-serifs for body text only', is_correct: false }, { id: 'd', text: 'There is no visual difference — only stylistic preference', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-des101-7', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'Visual hierarchy in UI design is primarily achieved through:', options: [{ id: 'a', text: 'Using only one font throughout the design', is_correct: false }, { id: 'b', text: 'Differences in size, weight, colour, and position to guide the viewer\'s eye', is_correct: true }, { id: 'c', text: 'Keeping all elements the same size for consistency', is_correct: false }, { id: 'd', text: 'Using as many colours as possible', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-des101-8', course_id: 'demo-des101', type: 'multiple_choice', question_text: 'A 12-column grid is preferred in UI design because:', options: [{ id: 'a', text: 'It is required by all design tools', is_correct: false }, { id: 'b', text: 'It is divisible by 2, 3, 4, and 6 — enabling flexible layouts for any screen width', is_correct: true }, { id: 'c', text: '12 is a lucky number in Nigerian culture', is_correct: false }, { id: 'd', text: 'It reduces file size in Figma', is_correct: false }], is_exam_question: true, difficulty: 3, points: 2 },
  ],
  'demo-dev101': [
    { id: 'demo-q-dev101-1', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'Which keyword is used to declare a variable that cannot be reassigned?', options: [{ id: 'a', text: 'var', is_correct: false }, { id: 'b', text: 'let', is_correct: false }, { id: 'c', text: 'const', is_correct: true }, { id: 'd', text: 'static', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-dev101-2', course_id: 'demo-dev101', type: 'multiple_choice', question_text: "What is the result of `'5' == 5` in JavaScript?", options: [{ id: 'a', text: 'true (type coercion converts the string to a number)', is_correct: true }, { id: 'b', text: 'false', is_correct: false }, { id: 'c', text: 'TypeError', is_correct: false }, { id: 'd', text: 'undefined', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-dev101-3', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'Which statement is used to execute a block of code a specific number of times?', options: [{ id: 'a', text: 'if', is_correct: false }, { id: 'b', text: 'while', is_correct: false }, { id: 'c', text: 'switch', is_correct: false }, { id: 'd', text: 'for', is_correct: true }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-dev101-4', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'What does the `else` statement do in an `if...else` block?', options: [{ id: 'a', text: 'It runs if the `if` condition is true', is_correct: false }, { id: 'b', text: 'It always runs regardless of conditions', is_correct: false }, { id: 'c', text: 'It runs if the `if` condition is false', is_correct: true }, { id: 'd', text: 'It defines a new condition to check', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-dev101-5', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'Which array method creates a NEW array by transforming each element?', options: [{ id: 'a', text: 'forEach()', is_correct: false }, { id: 'b', text: 'map()', is_correct: true }, { id: 'c', text: 'find()', is_correct: false }, { id: 'd', text: 'push()', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-dev101-6', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'What is a closure in JavaScript?', options: [{ id: 'a', text: 'A way to close the browser window', is_correct: false }, { id: 'b', text: 'A function that remembers its outer scope even after the outer function has finished executing', is_correct: true }, { id: 'c', text: 'A method to close a database connection', is_correct: false }, { id: 'd', text: 'A type of loop', is_correct: false }], is_exam_question: true, difficulty: 3, points: 2 },
    { id: 'demo-q-dev101-7', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'What does the spread operator `...` do when used with an object?', options: [{ id: 'a', text: 'Deletes all properties from the object', is_correct: false }, { id: 'b', text: 'Copies all enumerable own properties into a new object', is_correct: true }, { id: 'c', text: 'Converts the object to a string', is_correct: false }, { id: 'd', text: 'Locks the object from mutation', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-dev101-8', course_id: 'demo-dev101', type: 'multiple_choice', question_text: 'What is the main advantage of `async/await` over raw `.then()` chains?', options: [{ id: 'a', text: 'It runs code faster', is_correct: false }, { id: 'b', text: 'It eliminates asynchronous behaviour entirely', is_correct: false }, { id: 'c', text: 'It makes asynchronous code read like synchronous code, improving readability', is_correct: true }, { id: 'd', text: 'It only works in Node.js, not in browsers', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
  ],
  'demo-dev105': [
    { id: 'demo-q-dev105-1', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'What is the primary purpose of Node.js?', options: [{ id: 'a', text: 'To style web pages', is_correct: false }, { id: 'b', text: 'To run JavaScript code on the server', is_correct: true }, { id: 'c', text: 'To create animations in the browser', is_correct: false }, { id: 'd', text: 'To manage databases directly', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-dev105-2', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'In CommonJS, how do you make a function from one file available to another?', options: [{ id: 'a', text: 'return myFunction;', is_correct: false }, { id: 'b', text: 'export default myFunction;', is_correct: false }, { id: 'c', text: 'module.exports = myFunction;', is_correct: true }, { id: 'd', text: 'include(myFunction);', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-dev105-3', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'Which core Node.js module is used for interacting with the file system?', options: [{ id: 'a', text: 'http', is_correct: false }, { id: 'b', text: 'url', is_correct: false }, { id: 'c', text: 'path', is_correct: false }, { id: 'd', text: 'fs', is_correct: true }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-dev105-4', course_id: 'demo-dev105', type: 'multiple_choice', question_text: "What is the main advantage of Node.js's non-blocking I/O model?", options: [{ id: 'a', text: 'It makes code easier to write', is_correct: false }, { id: 'b', text: 'It can handle many concurrent connections efficiently without extra threads', is_correct: true }, { id: 'c', text: 'It uses less memory than all other server technologies', is_correct: false }, { id: 'd', text: 'It runs code faster in all situations', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-dev105-5', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'In Express.js, what is the purpose of the `next()` function in middleware?', options: [{ id: 'a', text: 'It sends a response to the client', is_correct: false }, { id: 'b', text: 'It passes control to the next middleware function in the stack', is_correct: true }, { id: 'c', text: 'It jumps to the next route definition', is_correct: false }, { id: 'd', text: 'It restarts the Express server', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-dev105-6', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'Which HTTP method should be used to update part of an existing resource (partial update)?', options: [{ id: 'a', text: 'PUT', is_correct: false }, { id: 'b', text: 'POST', is_correct: false }, { id: 'c', text: 'PATCH', is_correct: true }, { id: 'd', text: 'GET', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-dev105-7', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'Why should secrets like API keys and database passwords be stored in environment variables rather than hardcoded in source code?', options: [{ id: 'a', text: 'Environment variables load faster', is_correct: false }, { id: 'b', text: 'Hardcoded secrets get committed to version control where anyone can see them', is_correct: true }, { id: 'c', text: 'It is a requirement of the Express framework', is_correct: false }, { id: 'd', text: 'Environment variables are automatically encrypted', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-dev105-8', course_id: 'demo-dev105', type: 'multiple_choice', question_text: 'A REST API endpoint for retrieving a single user by ID should be:', options: [{ id: 'a', text: 'GET /api/get-user?user=123', is_correct: false }, { id: 'b', text: 'POST /api/user', is_correct: false }, { id: 'c', text: 'GET /api/users/123', is_correct: true }, { id: 'd', text: 'GET /api/fetchUser/123', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
  ],
  'demo-qa101': [
    { id: 'demo-q-qa101-1', course_id: 'demo-qa101', type: 'multiple_choice', question_text: 'What is the main difference between QA and QC?', options: [{ id: 'a', text: 'QA is process-oriented (prevent defects); QC is product-oriented (find defects)', is_correct: true }, { id: 'b', text: 'QA is done by developers; QC is done by testers', is_correct: false }, { id: 'c', text: 'QA tests UI only; QC tests APIs only', is_correct: false }, { id: 'd', text: 'There is no meaningful difference', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-qa101-2', course_id: 'demo-qa101', type: 'multiple_choice', question_text: 'Which phase of the STLC involves setting up the hardware and software environment to run tests?', options: [{ id: 'a', text: 'Test Planning', is_correct: false }, { id: 'b', text: 'Test Environment Setup', is_correct: true }, { id: 'c', text: 'Test Closure', is_correct: false }, { id: 'd', text: 'Requirement Analysis', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-qa101-3', course_id: 'demo-qa101', type: 'multiple_choice', question_text: '"White Box" testing primarily focuses on:', options: [{ id: 'a', text: 'The user interface and visual design', is_correct: false }, { id: 'b', text: 'Internal code structure and logic', is_correct: true }, { id: 'c', text: 'Business requirements from a user perspective', is_correct: false }, { id: 'd', text: 'The product installation process', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-qa101-4', course_id: 'demo-qa101', type: 'multiple_choice', question_text: 'After a developer fixes a bug, what is the next status in the Bug Life Cycle?', options: [{ id: 'a', text: 'Closed', is_correct: false }, { id: 'b', text: 'Verified', is_correct: false }, { id: 'c', text: 'Retest', is_correct: true }, { id: 'd', text: 'Deferred', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-qa101-5', course_id: 'demo-qa101', type: 'multiple_choice', question_text: 'A login button is broken on the homepage of a banking app. It has HIGH severity and HIGH priority. Which statement best explains why?', options: [{ id: 'a', text: 'All bugs on the homepage are high severity', is_correct: false }, { id: 'b', text: 'The bug completely blocks core functionality (high severity) and must be fixed immediately before users lose trust (high priority)', is_correct: true }, { id: 'c', text: 'Only priority matters; severity is irrelevant for banking apps', is_correct: false }, { id: 'd', text: 'The button style is broken, making it look bad', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
    { id: 'demo-q-qa101-6', course_id: 'demo-qa101', type: 'multiple_choice', question_text: 'In Boundary Value Analysis, if a field accepts values between 1 and 100, which values should be tested?', options: [{ id: 'a', text: '50 only', is_correct: false }, { id: 'b', text: '0, 1, 100, 101 (edges and just outside)', is_correct: true }, { id: 'c', text: 'All values from 1 to 100', is_correct: false }, { id: 'd', text: 'Only invalid values like -1 and 999', is_correct: false }], is_exam_question: true, difficulty: 3, points: 2 },
  ],
  'demo-scr101': [
    { id: 'demo-q-scr101-1', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'Which of the following is NOT one of the four values of the Agile Manifesto?', options: [{ id: 'a', text: 'Individuals and interactions over processes and tools', is_correct: false }, { id: 'b', text: 'Working software over comprehensive documentation', is_correct: false }, { id: 'c', text: 'Contract negotiation over customer collaboration', is_correct: true }, { id: 'd', text: 'Responding to change over following a plan', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-scr101-2', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'What are the three pillars of Scrum (Empiricism)?', options: [{ id: 'a', text: 'Planning, Execution, Delivery', is_correct: false }, { id: 'b', text: 'Transparency, Inspection, Adaptation', is_correct: true }, { id: 'c', text: 'Respect, Courage, Openness', is_correct: false }, { id: 'd', text: 'Roles, Events, Artifacts', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-scr101-3', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'Who is accountable for maximising the value of the product in Scrum?', options: [{ id: 'a', text: 'The Scrum Master', is_correct: false }, { id: 'b', text: 'The Developers', is_correct: false }, { id: 'c', text: 'The Product Owner', is_correct: true }, { id: 'd', text: 'The CEO', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-scr101-4', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'The Scrum Master is best described as a:', options: [{ id: 'a', text: 'Project Manager who assigns tasks', is_correct: false }, { id: 'b', text: 'Servant Leader who removes impediments and coaches the team', is_correct: true }, { id: 'c', text: 'Team Boss who approves all decisions', is_correct: false }, { id: 'd', text: 'Product Designer', is_correct: false }], is_exam_question: false, difficulty: 1, points: 1 },
    { id: 'demo-q-scr101-5', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'What is the purpose of the Definition of Done (DoD)?', options: [{ id: 'a', text: 'To list all the features the product should have', is_correct: false }, { id: 'b', text: 'To provide a shared standard that the Increment must meet to be considered complete', is_correct: true }, { id: 'c', text: 'To set the Sprint Goal', is_correct: false }, { id: 'd', text: 'To describe when a Sprint ends', is_correct: false }], is_exam_question: false, difficulty: 2, points: 1 },
    { id: 'demo-q-scr101-6', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'The Product Owner keeps adding items to the Sprint Backlog mid-Sprint, threatening the Sprint Goal. As Scrum Master, what is the BEST response?', options: [{ id: 'a', text: 'Add the items — the PO outranks the team', is_correct: false }, { id: 'b', text: 'Escalate to senior management', is_correct: false }, { id: 'c', text: 'Coach the PO on protecting the Sprint Goal and redirect new items to the Product Backlog for the next Sprint', is_correct: true }, { id: 'd', text: 'Cancel the Sprint immediately', is_correct: false }], is_exam_question: true, difficulty: 3, points: 2 },
    { id: 'demo-q-scr101-7', course_id: 'demo-scr101', type: 'multiple_choice', question_text: 'How does Kanban differ from Scrum primarily?', options: [{ id: 'a', text: 'Kanban has sprints; Scrum does not', is_correct: false }, { id: 'b', text: 'Kanban is a continuous flow system with WIP limits; Scrum uses time-boxed iterations', is_correct: true }, { id: 'c', text: 'Scrum is only for software; Kanban is for manufacturing', is_correct: false }, { id: 'd', text: 'There is no meaningful difference between them', is_correct: false }], is_exam_question: true, difficulty: 2, points: 2 },
  ],
};

// ─── Overview stats ───────────────────────────────────────────────────────────

export const DEMO_OVERVIEW = {
  totalUsers: 8,
  totalCourses: 31,
  pendingSuggestions: 2,
  pendingCapstones: 1,
  activeSubscriptions: 3,
  totalTransactions: 5,
};
