import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { initiatePayment } from '@/lib/paystack';

// POST /api/marketplace/checkout
// Body: { email: string; slug: string }
// Returns: { payment_url: string } or { already_purchased: true, download_token: string }
export async function POST(request: NextRequest) {
  let email = '';
  let slug = '';
  try {
    const body = await request.json();
    email = (body.email ?? '').trim().toLowerCase();
    slug = (body.slug ?? '').trim().toLowerCase();
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  if (!email || !/^[^@]+@[^@]+\.[^@]+$/.test(email)) {
    return NextResponse.json({ error: 'A valid email address is required' }, { status: 400 });
  }
  if (!slug) {
    return NextResponse.json({ error: 'Product slug is required' }, { status: 400 });
  }

  const admin = createAdminClient();

  // Fetch the product
  const { data: product } = await admin
    .from('marketplace_products')
    .select('id, name, price_ngn')
    .eq('slug', slug)
    .eq('is_active', true)
    .maybeSingle();

  if (!product) {
    return NextResponse.json({ error: 'Product not found' }, { status: 404 });
  }

  // Idempotent: check if this email already paid for this product
  const { data: existing } = await admin
    .from('marketplace_purchases')
    .select('download_token, token_expires_at')
    .eq('email', email)
    .eq('product_id', product.id)
    .eq('payment_status', 'paid')
    .maybeSingle();

  if (existing) {
    return NextResponse.json({
      already_purchased: true,
      download_token: existing.download_token,
      token_expires_at: existing.token_expires_at,
    });
  }

  const reference = `mkt-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const origin = request.nextUrl.origin;
  const callbackUrl = `${origin}/marketplace/success?ref=${reference}`;

  // Pre-create purchase row (download_token generated by DB default)
  const { error: insertError } = await admin
    .from('marketplace_purchases')
    .insert({
      product_id: product.id,
      email,
      paystack_reference: reference,
      payment_status: 'pending',
    });

  if (insertError) {
    console.error('[marketplace/checkout] DB insert error:', insertError);
    return NextResponse.json({ error: 'Failed to initialise purchase' }, { status: 500 });
  }

  try {
    const paystack = await initiatePayment({
      email,
      amount_kobo: product.price_ngn * 100,
      reference,
      metadata: {
        type: 'marketplace_product',
        product_id: product.id,
        email,
      },
      callback_url: callbackUrl,
    });

    return NextResponse.json({ payment_url: paystack.data.authorization_url });
  } catch (err) {
    console.error('[marketplace/checkout] Paystack error:', err);
    // Clean up pre-created row so the user can try again
    await admin.from('marketplace_purchases').delete().eq('paystack_reference', reference);
    return NextResponse.json({ error: 'Payment initiation failed. Please try again.' }, { status: 500 });
  }
}
